### ISSUE TITLE
element selection by first letter only? 

### ISSUE THREAD

**Issue by 2015hcm** [chris-stallard1/OpenAGS#1]
Chris,

Looks like the files in the master branch, with the exception of requirements.txt, do not correspond to the OpenAGS v.0.2.1 you sent me earlier.  As is, when I tried to run it, it returns an "ibottun6" error.  

I put the correct files you sent me earlier in this repo:
2015hcm/OpenAGS-Chris

in case you need would like to update your master branch.

Thanks,
Heather

**Comment by chris-stallard1** [comment]
Just closing this as the software is now completely different and doesn't have this issue anymore.

Thanks,
Chris
